### ISSUE TITLE
change codebase to follow a multiCommand  structure

### ISSUE THREAD

**Issue by Gwali-1** [Oval-Personal-Data-Wallet/key-guard#6]
The structure currently is one click command thats does different actions depending on the option flags provided.
This involves checking which option was passed in, resulting in a couple of if statements and in the case where functionality
has to be extended or modified , this will mean more if statements which in turn will make things messier. Making some of the tool functionality as sub-commands will greatly facilitate the development process and even make unit testing way easier.

**Comment by buabaj** [comment]
great! i assigned it to you, go crazy bro
